# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-25 15:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import filebrowser.fields
import tinymce.models
import vote.help


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid', models.IntegerField(default=0, verbose_name='会员ID')),
                ('title', models.CharField(default='', max_length=30, verbose_name='广告标题')),
                ('image', filebrowser.fields.FileBrowseField(blank=True, default='', max_length=200, verbose_name='图片')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
            ],
            options={
                'verbose_name_plural': '3.广告管理',
                'verbose_name': '广告管理',
            },
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid', models.IntegerField(default=0, verbose_name='会员ID')),
                ('openid', models.CharField(blank=True, db_index=True, default='', max_length=200, verbose_name='微信ID')),
                ('username', models.CharField(default='', max_length=30, verbose_name='姓名')),
                ('tel', models.CharField(blank=True, default='', max_length=30, verbose_name='电话')),
                ('image0', models.ImageField(blank=True, default='', max_length=500, upload_to=vote.help.PathAndRename('images/2018/01/25'), verbose_name='照片0')),
                ('image1', models.ImageField(blank=True, default='', max_length=500, upload_to=vote.help.PathAndRename('images/2018/01/25'), verbose_name='照片1')),
                ('image2', models.ImageField(blank=True, default='', max_length=500, upload_to=vote.help.PathAndRename('images/2018/01/25'), verbose_name='照片2')),
                ('image3', models.ImageField(blank=True, default='', max_length=500, upload_to=vote.help.PathAndRename('images/2018/01/25'), verbose_name='照片3')),
                ('image4', models.ImageField(blank=True, default='', max_length=500, upload_to=vote.help.PathAndRename('images/2018/01/25'), verbose_name='照片4')),
                ('info', models.CharField(blank=True, default='', max_length=1000, verbose_name='个人介绍')),
                ('num', models.IntegerField(default=1, verbose_name='投票号')),
                ('ticket', models.IntegerField(default=0, verbose_name='票数')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('status', models.IntegerField(choices=[(0, '禁用'), (1, '启用')], default=1, verbose_name='状态')),
            ],
            options={
                'verbose_name_plural': '4.选手',
                'verbose_name': '选手',
            },
        ),
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid', models.IntegerField(default=0, verbose_name='会员ID')),
                ('title', models.CharField(default='', max_length=30, verbose_name='名称')),
                ('ticket', models.IntegerField(default=1, verbose_name='票数')),
                ('price', models.FloatField(default='0.00', verbose_name='价格')),
                ('picurl', models.ImageField(blank=True, default='', max_length=500, upload_to=vote.help.PathAndRename('images/2018/01/25'), verbose_name='图片')),
                ('attr', models.IntegerField(choices=[(0, '不开启自定义'), (1, '开启自定义')], default=0, verbose_name='属性')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name_plural': '5.礼物',
                'verbose_name': '礼物',
                'ordering': ['sort'],
            },
        ),
        migrations.CreateModel(
            name='Ordering',
            fields=[
                ('mid', models.IntegerField(default=0, verbose_name='会员ID')),
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False, verbose_name='订单号')),
                ('vid', models.IntegerField(default=0, verbose_name='活动ID')),
                ('fid', models.IntegerField(default=0, verbose_name='选手ID')),
                ('openid', models.CharField(db_index=True, default='', max_length=100, verbose_name='微信openid')),
                ('gift_id', models.IntegerField(default=0, verbose_name='礼物ID')),
                ('num', models.IntegerField(default=0, verbose_name='数量')),
                ('status', models.IntegerField(choices=[(0, '未支付'), (1, '已支付')], default=0, verbose_name='状态')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('total_fee', models.FloatField(default='0.00', verbose_name='支付金额')),
            ],
            options={
                'verbose_name_plural': '8.订单',
                'verbose_name': '订单',
                'ordering': ['-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid', models.IntegerField(default=0, verbose_name='会员ID')),
                ('payment', models.CharField(choices=[('weixin', '微信支付'), ('alipay', '支付宝')], default='weixin', max_length=20, verbose_name='付款方式')),
                ('transaction_id', models.CharField(default='', max_length=60, verbose_name='商户订单号')),
                ('pay_time', models.CharField(default='', max_length=60, verbose_name='交易时间')),
                ('openid', models.CharField(default='', max_length=60, verbose_name='微信ID')),
                ('status', models.IntegerField(choices=[(0, '未支付'), (1, '已支付')], default=0, verbose_name='状态')),
                ('total_fee', models.FloatField(default='0.00', verbose_name='交易金额')),
                ('summary', models.CharField(default='', max_length=100, verbose_name='备注')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('orderid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.Ordering', verbose_name='支付单号')),
            ],
            options={
                'verbose_name_plural': '9.支付记录',
                'verbose_name': '支付记录',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid', models.IntegerField(default=0, verbose_name='会员ID')),
                ('fid', models.IntegerField(db_index=True, default=0, verbose_name='选手ID')),
                ('vid', models.IntegerField(db_index=True, default=0, verbose_name='活动ID')),
                ('openid', models.CharField(db_index=True, default='', max_length=60, verbose_name='微信ID')),
                ('IP', models.CharField(default='', max_length=15, verbose_name='投票人IP')),
                ('summary', models.CharField(default='', max_length=100, verbose_name='描述')),
                ('is_pay', models.IntegerField(choices=[(0, '否'), (1, '否')], default=0, verbose_name='是否支付投票')),
                ('pub_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='发布时间')),
            ],
            options={
                'verbose_name_plural': '7.投票记录',
                'verbose_name': '投票记录',
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=30, verbose_name='模板名称')),
                ('folder', models.CharField(default='', max_length=30, verbose_name='模板文件名')),
                ('picurl', models.ImageField(max_length=500, upload_to=vote.help.PathAndRename('images/2018/01/25'), verbose_name='模板缩略图')),
                ('status', models.IntegerField(choices=[(0, '禁用'), (1, '启用')], default=0, verbose_name='状态')),
            ],
            options={
                'verbose_name_plural': '1.界面风格',
                'verbose_name': '界面风格',
            },
        ),
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid', models.IntegerField(db_index=True, default=0, verbose_name='会员ID')),
                ('openid', models.CharField(db_index=True, default='', max_length=200)),
                ('avatarUrl', models.ImageField(db_index=True, max_length=500, upload_to=vote.help.PathAndRename('images/2018/01/25'), verbose_name='头像')),
                ('city', models.CharField(default='', max_length=20, verbose_name='城市')),
                ('country', models.CharField(default='', max_length=20, verbose_name='国家')),
                ('gender', models.CharField(choices=[('0', '未知'), ('1', '男'), ('2', '女')], default='0', max_length=1, verbose_name='姓别')),
                ('language', models.CharField(default='', max_length=20, verbose_name='语言')),
                ('nickName', models.CharField(default='', max_length=20, verbose_name='名称')),
                ('province', models.CharField(default='', max_length=20, verbose_name='省份')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('login_count', models.IntegerField(default=1, verbose_name='登陆次数')),
                ('login_date', models.DateTimeField(auto_now=True, verbose_name='最后登陆时间')),
            ],
            options={
                'verbose_name_plural': '6.微信用户',
                'verbose_name': '微信用户',
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid', models.IntegerField(default=0, verbose_name='会员ID')),
                ('title', models.CharField(default='', max_length=30, verbose_name='活动主题')),
                ('message', models.CharField(default='', max_length=100, verbose_name='公告')),
                ('image', filebrowser.fields.FileBrowseField(blank=True, default='', max_length=200, verbose_name='图片')),
                ('view', models.IntegerField(default=1, verbose_name='虚拟人气设置')),
                ('start_date', models.DateTimeField(verbose_name='活动开始时间')),
                ('end_date', models.DateTimeField(verbose_name='活动结束时间')),
                ('v_start_date', models.DateTimeField(verbose_name='投票开始时间')),
                ('v_end_date', models.DateTimeField(verbose_name='投票结束时间')),
                ('cknums', models.IntegerField(default=1, verbose_name='每人限制每天投多少票')),
                ('sort_field', models.CharField(choices=[('pub_date', '时间'), ('num', '投票号'), ('ticket', '票数')], default='pub_date', max_length=30, verbose_name='选手排序字段')),
                ('status', models.IntegerField(choices=[(0, '禁用'), (1, '启用')], default=0, verbose_name='状态')),
                ('sign_status', models.IntegerField(choices=[(0, '不审核'), (1, '审核')], default=0, verbose_name='选手报名是否审核')),
                ('sign_repeat', models.IntegerField(default=1, verbose_name='一个微信号允许多少次报名')),
                ('sort', models.IntegerField(choices=[(0, '升序'), (1, ' 降序')], default=0, verbose_name='排序')),
                ('content', tinymce.models.HTMLField(blank=True, default='', verbose_name='活动规则')),
                ('prize', tinymce.models.HTMLField(blank=True, default='', verbose_name='奖品')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('template_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.Template', verbose_name='模板界面风格')),
            ],
            options={
                'verbose_name_plural': '2.投票活动',
                'verbose_name': '投票活动',
            },
        ),
        migrations.AddField(
            model_name='gift',
            name='vid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.Vote', verbose_name='活动'),
        ),
        migrations.AddField(
            model_name='form',
            name='vid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.Vote', verbose_name='活动'),
        ),
        migrations.AddField(
            model_name='ad',
            name='vid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.Vote', verbose_name='活动'),
        ),
    ]
