# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-01 09:54
from __future__ import unicode_literals

from django.db import migrations, models
import vote.help


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0003_auto_20180131_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='image0',
            field=models.ImageField(blank=True, default='', max_length=500, upload_to=vote.help.PathAndRename('images/2018/02/01'), verbose_name='照片0'),
        ),
        migrations.AlterField(
            model_name='form',
            name='image1',
            field=models.ImageField(blank=True, default='', max_length=500, upload_to=vote.help.PathAndRename('images/2018/02/01'), verbose_name='照片1'),
        ),
        migrations.AlterField(
            model_name='form',
            name='image2',
            field=models.ImageField(blank=True, default='', max_length=500, upload_to=vote.help.PathAndRename('images/2018/02/01'), verbose_name='照片2'),
        ),
        migrations.AlterField(
            model_name='form',
            name='image3',
            field=models.ImageField(blank=True, default='', max_length=500, upload_to=vote.help.PathAndRename('images/2018/02/01'), verbose_name='照片3'),
        ),
        migrations.AlterField(
            model_name='form',
            name='image4',
            field=models.ImageField(blank=True, default='', max_length=500, upload_to=vote.help.PathAndRename('images/2018/02/01'), verbose_name='照片4'),
        ),
        migrations.AlterField(
            model_name='gift',
            name='picurl',
            field=models.ImageField(blank=True, default='', max_length=500, upload_to=vote.help.PathAndRename('images/2018/02/01'), verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='template',
            name='picurl',
            field=models.ImageField(max_length=500, upload_to=vote.help.PathAndRename('images/2018/02/01'), verbose_name='模板缩略图'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='avatarUrl',
            field=models.ImageField(db_index=True, max_length=500, upload_to=vote.help.PathAndRename('images/2018/02/01'), verbose_name='头像'),
        ),
    ]
