# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-07 22:36
from __future__ import unicode_literals

from django.db import migrations, models
import vote.help


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0004_auto_20180201_0954'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid', models.IntegerField(default=0, verbose_name='会员ID')),
                ('appId', models.CharField(blank=True, default='', max_length=30, verbose_name='AppID(小程序ID')),
                ('appSecret', models.CharField(blank=True, default='', max_length=80, verbose_name='AppSecret(小程序密钥)')),
                ('mch_id', models.CharField(blank=True, default='', max_length=20, verbose_name='商户ID')),
                ('merchant_key', models.CharField(blank=True, default='', max_length=80, verbose_name='商户支付密钥')),
            ],
            options={
                'verbose_name': '系统参数设置',
                'verbose_name_plural': '0.系统参数设置',
            },
        ),
        migrations.AlterField(
            model_name='form',
            name='image0',
            field=models.ImageField(blank=True, default='', max_length=500, upload_to=vote.help.PathAndRename('images/2018/02/07'), verbose_name='照片0'),
        ),
        migrations.AlterField(
            model_name='form',
            name='image1',
            field=models.ImageField(blank=True, default='', max_length=500, upload_to=vote.help.PathAndRename('images/2018/02/07'), verbose_name='照片1'),
        ),
        migrations.AlterField(
            model_name='form',
            name='image2',
            field=models.ImageField(blank=True, default='', max_length=500, upload_to=vote.help.PathAndRename('images/2018/02/07'), verbose_name='照片2'),
        ),
        migrations.AlterField(
            model_name='form',
            name='image3',
            field=models.ImageField(blank=True, default='', max_length=500, upload_to=vote.help.PathAndRename('images/2018/02/07'), verbose_name='照片3'),
        ),
        migrations.AlterField(
            model_name='form',
            name='image4',
            field=models.ImageField(blank=True, default='', max_length=500, upload_to=vote.help.PathAndRename('images/2018/02/07'), verbose_name='照片4'),
        ),
        migrations.AlterField(
            model_name='gift',
            name='picurl',
            field=models.ImageField(blank=True, default='', max_length=500, upload_to=vote.help.PathAndRename('images/2018/02/07'), verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='template',
            name='picurl',
            field=models.ImageField(max_length=500, upload_to=vote.help.PathAndRename('images/2018/02/07'), verbose_name='模板缩略图'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='avatarUrl',
            field=models.ImageField(db_index=True, max_length=500, upload_to=vote.help.PathAndRename('images/2018/02/07'), verbose_name='头像'),
        ),
    ]
