# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-08 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0006_auto_20180208_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='notify_url',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='回调支付url地址'),
        ),
    ]
