module.exports={
  appId:'',
  secret:'',
  mch_id: '',
  merchant_key: '',
    page_size : 10,//默认每页显示调试
    mid:1,
    api:{
        url:'https://jiahe.zz.lanrenmb.com',
        index:'https://jiahe.zz.lanrenmb.com/vote/index/',
        detail:'https://jiahe.zz.lanrenmb.com/vote/detail/',
        rank:'https://jiahe.zz.lanrenmb.com/vote/rank/',
        sign:'https://jiahe.zz.lanrenmb.com/vote/sign/',
        api_weixin:'https://jiahe.zz.lanrenmb.com/vote/api_weixin/',
        api_weixin2:'https://jiahe.zz.lanrenmb.com/vote/api_weixin2/',
        vote_post:'https://jiahe.zz.lanrenmb.com/vote/vote_post/',
        vote_list:'https://jiahe.zz.lanrenmb.com/vote/vote_list/',
        search:'https://jiahe.zz.lanrenmb.com/vote/search/',
        search_index:'https://jiahe.zz.lanrenmb.com/vote/search_index/',
        image_post:'https://jiahe.zz.lanrenmb.com/vote/image_post/',
        sign_post:'https://jiahe.zz.lanrenmb.com/vote/sign_post/',
        gift:'https://jiahe.zz.lanrenmb.com/vote/gift/',
        wxpay:'https://jiahe.zz.lanrenmb.com/vote/wxpay/',
        wxpay2:'https://jiahe.zz.lanrenmb.com/vote/wxpay2/',
        wxpay_notify:'https://jiahe.zz.lanrenmb.com/vote/wxpay_notify/',
        userinfo:'https://jiahe.zz.lanrenmb.com/vote/userinfo/',
        userinfo_post:'https://jiahe.zz.lanrenmb.com/vote/userinfo_post/',
        ordering_post:'https://jiahe.zz.lanrenmb.com/vote/ordering_post/',
        ordering_update:'https://jiahe.zz.lanrenmb.com/vote/ordering_update/',
    }
}
